# Configuration pour le développement
version: '3.8'

services:
  # Service de build des packages partagés
  shared-dev:
    build:
      context: .
      dockerfile: packages/shared/Dockerfile.dev
    container_name: sharedPackageDev
    volumes:
      - ./packages:/app/packages
      - node_modules:/app/node_modules
    command: pnpm run dev
    networks:
      - app-network

  # Client frontend (Dev)
  client-frontend-dev:
    build:
      context: .
      dockerfile: apps/client/Dockerfile.dev
    container_name: clientFrontendDev
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=/client/
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - shared-dev

  # Restaurant frontend (Dev)
  restaurateur-frontend-dev:
    build:
      context: .
      dockerfile: apps/restaurateur/Dockerfile.dev
    container_name: restaurateurFrontendDev
    ports:
      - "5174:5174"
    environment:
      - VITE_BASE_URL=/restaurateur/
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - shared-dev

  # Livreur frontend (Dev)
  livreur-frontend-dev:
    build:
      context: .
      dockerfile: apps/livreur/Dockerfile.dev
    container_name: livreurFrontendDev
    ports:
      - "5175:5175"
    environment:
      - VITE_BASE_URL=/livreur/
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - shared-dev

  # Commercial frontend (Dev)
  commercial-frontend-dev:
    build:
      context: .
      dockerfile: apps/commercial/Dockerfile.dev
    container_name: commercialFrontendDev
    ports:
      - "5188:5178"  # Changez 5178 en 5188 pour le mapping externe
    environment:
      - VITE_BASE_URL=/commercial/
      - VITE_API_URL=http://localhost:8080/api
      - VITE_REDIRECT_URI_RESTAURATEUR=http://localhost:8080/commercial/
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - shared-dev

  # Developer frontend (Dev)
  developer-frontend-dev:
    build:
      context: .
      dockerfile: apps/developer/Dockerfile.dev
    container_name: developerFrontendDev
    ports:
      - "5176:5176"
    environment:
      - VITE_BASE_URL=/developer/
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - shared-dev

  # Technical frontend (Dev)
  technical-frontend-dev:
    build:
      context: .
      dockerfile: apps/technical/Dockerfile.dev
    container_name: technicalFrontendDev
    ports:
      - "5177:5177"
    environment:
      - VITE_BASE_URL=/technical/
      - VITE_API_URL=http://localhost:8080/api
      - HOST=0.0.0.0
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - shared-dev